---
version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: glenux/teaching-boilerplate
    environment: {}
    ports:
      - 5100:5100
      - 5200:5200

#
